import { JetBrains_Mono } from "next/font/google";
import "./menu.css";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const JetBrains = JetBrains_Mono({
  variable: "--font-JetBrains",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${JetBrains.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
